[project]
name = "shoppingagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ASAM", email = "asam.ugeng8385@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "agent-framework-azure-contentunderstanding>=1.0.0b260813",
    "azure-ai-agents>=1.1.0",
    "azure-ai-contentsafety>=1.0.0",
    "azure-ai-contentunderstanding>=1.2.0b3",
    "azure-ai-projects>=2.4.0",
    "azure-identity>=1.25.3",
    "datetime>=6.0",
    "fastapi>=0.141.1",
    "fastembed>=0.8.0",
    "jinja2>=3.1.6",
    "mysql-connector-python>=26.7.0",
    "python-dotenv>=1.2.2",
    "qdrant-client>=1.19.0",
    "sentence-transformers>=5.7.0",
    "torch==2.11.0",
    "uvicorn[standard]>=0.52.1",
]

[project.scripts]
shoppingagent = "shoppingagent.main:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"


